#!/usr/bin/env bash
# read /etc/passwd and show username, user id and home directory
while IFS=: read -r user pass uid gid comment home shell; do
  echo "The user $user is part of the $gid gang, lives in $home and rides $shell. $uid 's place is protected by the passcode $pass, more info about the user here: $comment"
  
done < /etc/passwd
