#!/usr/bin/env bash
#This sript prints Best School for 10 times
x=1
while [ $x -le 10 ]; do
  echo "Best School"
  if [ $x -eq 4 ]; then
    echo "bad Luck"
  elif [ $x -eq 8 ]; then
    echo "good Luck"
  fi
  x=$(( x + 1 ))
done
