#!/usr/bin/env bash
# Script that checks if a file exists and prints its status

FILE="school"

if [ -e "$FILE" ]; then
    echo "school file exists"
    if [ -d "$FILE" ]; then
        echo "school is a directory"
    elif [ -f "$FILE" ]; then
        echo "school is a regular file"
        if [ -s "$FILE" ]; then
            echo "school file is not empty"
        else
            echo "school file is empty"
        fi
    fi
else
    echo "school file does not exist"
fi

